name: DropboxBackUp
author: alvin0319
main: alvin0319\DropboxBackUp\DropboxBackUp
version: 1.0.1
api: 3.0.0

commands:
  db:
    description: Starting backup on Dropbox
    permission: dropbox.cmd

permissions:
  dropbox.cmd:
    default: op
